[project]
name = "yamlr"
version = "0.1.0"
description = "yamlr a yaml schema validator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyyaml>=6.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]