name: Update MAX

on:
  push:
    paths-ignore:
      - .gitignore
      - .github/**
      - docs/**
      - README.md

  pull_request:
      branches:
        - main

  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: 
      - ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - run: pytest

  release:
    name: Release new version
    runs-on: 
      - ubuntu-latest
    
    needs: ['test']

    permissions:
      contents: write
    
    if: github.ref == 'main'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Zip Contents into deploy.zip
        if: matrix.jobs.type == 'release'
        run: |
          ls -R
          zip deploy.zip -r yamlr

      - run: python3 tools/create_release.py
        shell: bash
        env:
          APP_TOKEN: github.token
