name: CI Build

on:
  push:
    paths-ignore:
      - .gitignore
      - .github/**
      - docs/**
      - README.md

  pull_request:
      branches:
        - main

  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: 
      - ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Print Environment
        shell: bash
        run: env

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji pyyaml

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: true
          report-title: 'Test Report'

  release:
    name: Release new version
    runs-on: 
      - ubuntu-latest
    
    needs: ['test']

    permissions:
      contents: write
      issues: write
      pull-requests: write

    if: github.ref == 'main'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Zip Contents into yamlr.zip
        shell: bash
        run: |
          ls -R
          zip yamlr.zip -r yamlr

      - name: Release version
        shell: bash
        run: python3 tools/create_release.py
        env:
          GITHUB_TOKEN: ${{ github.token }}
